import type { BlockDefinition, Field } from './types';

const alignField: Field = {
  name: 'align',
  label: 'Text alignment',
  type: 'select',
  width: 'half',
  default: 'left',
  options: [
    { label: 'Left', value: 'left' },
    { label: 'Centre', value: 'center' },
  ],
};

const bgField: Field = {
  name: 'background',
  label: 'Background',
  type: 'select',
  width: 'half',
  default: 'white',
  options: [
    { label: 'White', value: 'white' },
    { label: 'Surface grey', value: 'surface' },
    { label: 'Ink (dark)', value: 'ink' },
    { label: 'Brand yellow', value: 'yellow' },
  ],
};

const linkFields: Field[] = [
  { name: 'label', label: 'Label', type: 'text', width: 'half' },
  {
    name: 'href',
    label: 'Link',
    type: 'link',
    width: 'half',
    help: 'Use "#quote" to open the quote drawer.',
  },
];

const tileFields: Field[] = [
  { name: 'eyebrow', label: 'Eyebrow', type: 'text', width: 'half' },
  { name: 'title', label: 'Title', type: 'text', width: 'half' },
  { name: 'links', label: 'Link line', type: 'tags', help: 'Shown separated by “|”.' },
  { name: 'image', label: 'Image', type: 'image' },
  { name: 'href', label: 'Links to', type: 'link', width: 'half', default: '/collections' },
  {
    name: 'align',
    label: 'Text side',
    type: 'select',
    width: 'half',
    default: 'left',
    options: [
      { label: 'Left', value: 'left' },
      { label: 'Right', value: 'right' },
    ],
  },
];

export const BLOCKS: BlockDefinition[] = [
  // ------------------------------------------------------------- hero & headers
  {
    type: 'hero',
    label: 'Hero banner',
    group: 'Hero & headers',
    glyph: '▤',
    description: 'Full-bleed photo hero with badge, headline, two CTAs and a star-rating proof line.',
    fields: [
      { name: 'badge', label: 'Badge', type: 'text' },
      { name: 'heading', label: 'Headline', type: 'textarea', rows: 2 },
      { name: 'body', label: 'Sub-headline', type: 'textarea', rows: 2 },
      { name: 'image', label: 'Background photo', type: 'image' },
      { name: 'primary', label: 'Primary button', type: 'list', fields: linkFields },
      { name: 'secondary', label: 'Secondary button', type: 'list', fields: linkFields },
      { name: 'proof', label: 'Proof line', type: 'text', width: 'half' },
      { name: 'height', label: 'Height (px)', type: 'number', width: 'half', min: 380, max: 1000 },
      {
        name: 'cornerYear',
        label: 'Corner tab — big',
        type: 'text',
        width: 'half',
        help: 'Leave both corner fields empty to hide the tab.',
      },
      { name: 'cornerLabel', label: 'Corner tab — small', type: 'text', width: 'half' },
      { name: 'parallax', label: 'Parallax background', type: 'boolean', width: 'half' },
    ],
    defaults: {
      badge: 'PREMIUM CUSTOM SPORTSWEAR WITH FREE MOCKUPS',
      heading: 'From concept to creation — we design top-tier uniforms.',
      body: 'From concept to creation, we deliver top-tier customized sportswear built for comfort, durability, and game-day confidence.',
      image: '/media/hero-field.png',
      primary: [{ label: 'Get my free mockup', href: '#quote' }],
      secondary: [{ label: 'Explore collections', href: '/collections' }],
      proof: '1,000+ happy customers',
      height: 720,
      cornerYear: '',
      cornerLabel: '',
      parallax: true,
    },
  },
  {
    type: 'pageHeader',
    label: 'Page header',
    group: 'Hero & headers',
    glyph: '▭',
    description: 'Breadcrumb, H1 and intro — light or dark. Used on Collection, Packages, About.',
    fields: [
      {
        name: 'theme',
        label: 'Theme',
        type: 'select',
        width: 'half',
        default: 'light',
        options: [
          { label: 'Light (surface grey)', value: 'light' },
          { label: 'Dark (ink)', value: 'dark' },
        ],
      },
      { name: 'eyebrow', label: 'Eyebrow', type: 'text', width: 'half' },
      { name: 'heading', label: 'Heading', type: 'text' },
      { name: 'body', label: 'Intro', type: 'textarea', rows: 3 },
      { name: 'showBreadcrumb', label: 'Show breadcrumb', type: 'boolean', width: 'half' },
      { name: 'image', label: 'Banner image', type: 'image', width: 'half' },
    ],
    defaults: {
      theme: 'light',
      eyebrow: '',
      heading: 'Page title',
      body: '',
      showBreadcrumb: true,
      image: '',
    },
  },

  // ------------------------------------------------------------- social proof / stats
  {
    type: 'statStrip',
    label: 'Stat strip',
    group: 'Social proof',
    glyph: '▦',
    description:
      'Compact USP row — bordered cells with animated count-up numbers. Mark one cell yellow to make it the hero stat.',
    fields: [
      bgField,
      {
        name: 'items',
        label: 'Stats',
        type: 'list',
        fields: [
          { name: 'value', label: 'Value', type: 'text', width: 'half' },
          { name: 'label', label: 'Label', type: 'text', width: 'half' },
          {
            name: 'count',
            label: 'Count up to',
            type: 'number',
            width: 'half',
            help: 'Leave 0 to display the value as-is.',
          },
          { name: 'suffix', label: 'Suffix', type: 'text', width: 'half' },
          { name: 'highlight', label: 'Yellow cell', type: 'boolean', width: 'half' },
        ],
      },
    ],
    defaults: {
      background: 'white',
      items: [
        { value: '1,000+', label: 'Teams outfitted', count: 1000, suffix: '+', highlight: false },
        { value: '3–4 weeks', label: 'Order to deliver', count: 0, suffix: '', highlight: false },
        { value: '24 hrs', label: 'Mockup turnaround', count: 24, suffix: ' hrs', highlight: false },
        { value: '$0', label: 'Art & setup fees', count: 0, suffix: '', highlight: true },
      ],
    },
  },
  {
    type: 'numbersGrid',
    label: 'By the numbers',
    group: 'Social proof',
    glyph: '⋕',
    description:
      'A grid of headline figures with captions — any number of cells, with optional count-up animation.',
    fields: [
      { name: 'eyebrow', label: 'Eyebrow', type: 'text', width: 'half' },
      { name: 'heading', label: 'Heading', type: 'text', width: 'half' },
      { name: 'body', label: 'Intro', type: 'textarea', rows: 2 },
      alignField,
      bgField,
      {
        name: 'minWidth',
        label: 'Min cell width (px)',
        type: 'number',
        width: 'half',
        min: 140,
        max: 400,
      },
      {
        name: 'items',
        label: 'Figures',
        type: 'list',
        fields: [
          { name: 'value', label: 'Figure', type: 'text', width: 'half' },
          { name: 'label', label: 'Caption', type: 'text', width: 'half' },
          {
            name: 'count',
            label: 'Count up to',
            type: 'number',
            width: 'half',
            help: 'Leave 0 to show the figure as typed.',
          },
          { name: 'suffix', label: 'Suffix', type: 'text', width: 'half' },
        ],
      },
    ],
    defaults: {
      eyebrow: 'By the numbers',
      heading: 'The short version',
      body: '',
      align: 'center',
      background: 'ink',
      minWidth: 220,
      items: [
        { value: '8+', label: 'Years of industry experience', count: 0, suffix: '' },
        { value: '1,000+', label: 'Happy customers', count: 1000, suffix: '+' },
        { value: '50+', label: 'Premium sportswear products', count: 50, suffix: '+' },
        { value: '100%', label: 'Custom designs', count: 0, suffix: '' },
      ],
    },
  },
  {
    type: 'marquee',
    label: 'Scrolling strip',
    group: 'Social proof',
    glyph: '≋',
    description: 'Infinite horizontal marquee of short phrases separated by ✦.',
    fields: [
      { name: 'items', label: 'Phrases', type: 'tags' },
      { name: 'speed', label: 'Loop seconds', type: 'number', width: 'half', min: 8, max: 120 },
    ],
    defaults: {
      items: [
        'Travel Teams',
        'High School Programs',
        'Rec Leagues',
        'Showcase Clubs',
        'Adult Leagues',
      ],
      speed: 28,
    },
  },
  {
    type: 'reviews',
    label: 'Review carousel',
    group: 'Social proof',
    glyph: '★',
    description: 'Auto-scrolling review cards pulled from the Reviews collection. Pauses on hover.',
    fields: [
      { name: 'eyebrow', label: 'Eyebrow', type: 'text', width: 'half' },
      { name: 'heading', label: 'Heading', type: 'text', width: 'half' },
      { name: 'ratingLine', label: 'Rating line', type: 'text' },
      { name: 'speed', label: 'Loop seconds', type: 'number', width: 'half', min: 15, max: 180 },
      { name: 'limit', label: 'Max reviews', type: 'number', width: 'half', min: 3, max: 30 },
    ],
    defaults: {
      eyebrow: 'Reviews',
      heading: 'Here is what our community says',
      ratingLine: '4.9 average from 1,000+ teams across softball & baseball',
      speed: 46,
      limit: 12,
    },
  },

  // ------------------------------------------------------------- commerce
  {
    type: 'featuredTiles',
    label: 'Photo tile mosaic',
    group: 'Commerce',
    glyph: '▩',
    description: 'Two tall tiles plus a stacked pair — each a photo with an overlaid label block.',
    fields: [
      { name: 'heading', label: 'Heading', type: 'text' },
      alignField,
      { name: 'tiles', label: 'Tiles', type: 'list', fields: tileFields },
    ],
    defaults: {
      heading: 'Featured Items',
      align: 'center',
      tiles: [
        {
          eyebrow: 'Rolling',
          title: 'Bat Bags',
          links: ['Shop now'],
          image: '/media/tile-bags.png',
          href: '/collections/bags',
          align: 'left',
        },
        {
          eyebrow: 'Custom',
          title: 'Softball',
          links: ['Design now'],
          image: '/media/tile-softball.png',
          href: '/collections/shirts',
          align: 'right',
        },
        {
          eyebrow: 'New',
          title: 'Full Sub Jerseys',
          links: ['Baseball', 'Softball', 'More'],
          image: '/media/tile-jerseys.png',
          href: '/collections/shirts',
          align: 'left',
        },
        {
          eyebrow: 'Shop',
          title: 'Team Packages',
          links: ['Alpha', 'Deal 1', 'Deal 2', 'Deal 3'],
          image: '/media/tile-packages.png',
          href: '/team-packages',
          align: 'left',
        },
      ],
    },
  },
  {
    type: 'tileGroups',
    label: 'Two tile columns',
    group: 'Commerce',
    glyph: '◫',
    description: '“For Teams / For Players” — two headed columns, each a 2×2 tile grid.',
    fields: [
      {
        name: 'groups',
        label: 'Columns',
        type: 'list',
        fields: [
          { name: 'heading', label: 'Column heading', type: 'text' },
          { name: 'tiles', label: 'Tiles', type: 'list', fields: tileFields },
        ],
      },
    ],
    defaults: {
      groups: [
        {
          heading: 'For Teams',
          tiles: [
            {
              eyebrow: '',
              title: 'Custom Uniforms',
              links: ['Mens', 'Womens', 'Boys', 'Girls'],
              image: '/media/tile-uniforms.png',
              href: '/collections/shirts',
              align: 'left',
            },
            {
              eyebrow: '',
              title: 'Custom Apparel',
              links: ['Hoodies', 'Pullovers', 'Polos'],
              image: '/media/tile-apparel.png',
              href: '/collections/jackets',
              align: 'left',
            },
            {
              eyebrow: '',
              title: 'Custom Bags',
              links: ['Bat Bags', 'Catcher Bags'],
              image: '/media/tile-bags.png',
              href: '/collections/bags',
              align: 'left',
            },
            {
              eyebrow: '',
              title: 'Custom Pants',
              links: ['Full Sub', 'Stock', 'Shorts'],
              image: '/media/tile-pants.png',
              href: '/collections/pants',
              align: 'left',
            },
          ],
        },
        {
          heading: 'For Players',
          tiles: [
            {
              eyebrow: '',
              title: 'Jerseys',
              links: ['Crew', '2-Button', 'Button-Up'],
              image: '/media/tile-jerseys.png',
              href: '/collections/shirts',
              align: 'left',
            },
            {
              eyebrow: '',
              title: 'Hoodies',
              links: ['Fleece', 'Windbreaker'],
              image: '/media/tile-apparel.png',
              href: '/collections/jackets',
              align: 'left',
            },
            {
              eyebrow: '',
              title: 'Sweatpants',
              links: ['Full Sub', 'Team Colors'],
              image: '/media/tile-pants.png',
              href: '/collections/pants',
              align: 'left',
            },
            {
              eyebrow: '',
              title: 'Softball Kits',
              links: ['Uniforms', 'Pants', 'Tops'],
              image: '/media/tile-softball.png',
              href: '/collections/shirts',
              align: 'left',
            },
          ],
        },
      ],
    },
  },
  {
    type: 'categoryCards',
    label: 'Category cards',
    group: 'Commerce',
    glyph: '▤',
    description: 'Large image-over-text cards with an underlined “Explore →” link.',
    fields: [
      { name: 'eyebrow', label: 'Eyebrow', type: 'text', width: 'half' },
      { name: 'heading', label: 'Heading', type: 'text', width: 'half' },
      {
        name: 'height',
        label: 'Image height (px)',
        type: 'number',
        width: 'half',
        min: 200,
        max: 720,
        help: 'Capped on phones so the card never fills the screen.',
      },
      {
        name: 'cards',
        label: 'Cards',
        type: 'list',
        fields: [
          { name: 'title', label: 'Title', type: 'text', width: 'half' },
          { name: 'linkLabel', label: 'Link label', type: 'text', width: 'half' },
          { name: 'body', label: 'Body', type: 'textarea', rows: 2 },
          { name: 'image', label: 'Image', type: 'image', width: 'half' },
          { name: 'href', label: 'Links to', type: 'link', width: 'half' },
        ],
      },
    ],
    defaults: {
      eyebrow: 'By sport',
      heading: 'Explore categories',
      height: 460,
      cards: [
        {
          title: 'Softball',
          body: 'Built for the circle and the box',
          image: '/media/cat-softball.png',
          href: '/collections/softball',
          linkLabel: 'Explore softball',
        },
        {
          title: 'Baseball',
          body: 'Moisture-wicking, game-ready',
          image: '/media/cat-baseball.png',
          href: '/collections/baseball',
          linkLabel: 'Explore baseball',
        },
      ],
    },
  },
  {
    type: 'productGrid',
    label: 'Product grid',
    group: 'Commerce',
    glyph: '⊞',
    description: 'Pulls live products — featured, a collection, or a hand-picked list.',
    fields: [
      { name: 'heading', label: 'Heading', type: 'text', width: 'half' },
      alignField,
      {
        name: 'source',
        label: 'Products from',
        type: 'select',
        width: 'half',
        default: 'featured',
        options: [
          { label: 'Featured products', value: 'featured' },
          { label: 'A collection', value: 'collection' },
          { label: 'Hand-picked', value: 'manual' },
          { label: 'Newest', value: 'newest' },
        ],
      },
      {
        name: 'collectionHandle',
        label: 'Collection handle',
        type: 'text',
        width: 'half',
        showIf: { field: 'source', equals: ['collection'] },
      },
      {
        name: 'handles',
        label: 'Product handles',
        type: 'tags',
        showIf: { field: 'source', equals: ['manual'] },
        help: 'In display order.',
      },
      { name: 'limit', label: 'How many', type: 'number', width: 'half', min: 1, max: 24 },
      {
        name: 'cardStyle',
        label: 'Card style',
        type: 'select',
        width: 'half',
        default: 'plate',
        options: [
          { label: 'Plate (centred, “From $”)', value: 'plate' },
          { label: 'Catalog (bordered, button)', value: 'catalog' },
        ],
      },
      { name: 'ctaLabel', label: 'Button label', type: 'text', width: 'half' },
      { name: 'ctaHref', label: 'Button link', type: 'link', width: 'half' },
      bgField,
    ],
    defaults: {
      heading: 'Items you might like',
      align: 'center',
      source: 'featured',
      collectionHandle: '',
      handles: [],
      limit: 4,
      cardStyle: 'plate',
      ctaLabel: 'Shop all products',
      ctaHref: '/collections',
      background: 'white',
    },
  },
  {
    type: 'packagesGrid',
    label: 'Team packages',
    group: 'Commerce',
    glyph: '▣',
    description: 'Per-player package cards from the Team Packages collection. Each opens the quote drawer.',
    fields: [
      { name: 'eyebrow', label: 'Eyebrow', type: 'text', width: 'half' },
      { name: 'heading', label: 'Heading', type: 'text', width: 'half' },
      { name: 'body', label: 'Intro', type: 'textarea', rows: 2 },
      bgField,
      { name: 'limit', label: 'How many', type: 'number', width: 'half', min: 1, max: 12 },
    ],
    defaults: {
      eyebrow: 'Team packages',
      heading: 'Kit the whole roster',
      body: '',
      background: 'surface',
      limit: 4,
    },
  },
  {
    type: 'collectionList',
    label: 'Collection list',
    group: 'Commerce',
    glyph: '☷',
    description: 'Cards linking to each published collection — like a Shopify catalog index.',
    fields: [
      { name: 'eyebrow', label: 'Eyebrow', type: 'text', width: 'half' },
      { name: 'heading', label: 'Heading', type: 'text', width: 'half' },
      { name: 'limit', label: 'How many', type: 'number', width: 'half', min: 1, max: 24 },
      bgField,
    ],
    defaults: {
      eyebrow: 'Shop',
      heading: 'All collections',
      limit: 12,
      background: 'white',
    },
  },

  // ------------------------------------------------------------- conversion
  {
    type: 'steps',
    label: 'How it works',
    group: 'Conversion',
    glyph: '➊',
    description: 'Numbered process steps with line icons.',
    fields: [
      { name: 'eyebrow', label: 'Eyebrow', type: 'text', width: 'half' },
      { name: 'heading', label: 'Heading', type: 'text', width: 'half' },
      {
        name: 'steps',
        label: 'Steps',
        type: 'list',
        fields: [
          { name: 'title', label: 'Title', type: 'text', width: 'half' },
          {
            name: 'icon',
            label: 'Icon',
            type: 'icon',
            width: 'half',
            default: 'chat',
          },
          { name: 'body', label: 'Body', type: 'textarea', rows: 2 },
        ],
      },
      bgField,
    ],
    defaults: {
      eyebrow: 'How it works',
      heading: 'Four steps to kit-out your team',
      background: 'white',
      steps: [
        {
          title: 'Send your idea',
          icon: 'chat',
          body: 'Roster size, sport and any logo or colors you already have. Two minutes on the quote form.',
        },
        {
          title: 'Free mockup in 24h',
          icon: 'clock',
          body: 'Our art team designs your kit and sends a firm per-unit price. Revisions are free.',
        },
        {
          title: 'Approve & we build',
          icon: 'check',
          body: 'Sublimation, cut and sew in 3–4 weeks — or 2 weeks on a rush order.',
        },
        {
          title: 'Delivered as a team',
          icon: 'truck',
          body: 'Bagged and labeled by player name, shipped anywhere in the US.',
        },
      ],
    },
  },
  {
    type: 'iconFeatures',
    label: 'Icon feature row',
    group: 'Conversion',
    glyph: '◈',
    description:
      'Value-prop cards with yellow icon chips. Three sizes — from a compact strip to full feature cards.',
    fields: [
      { name: 'eyebrow', label: 'Eyebrow', type: 'text', width: 'half' },
      { name: 'heading', label: 'Heading (optional)', type: 'text', width: 'half' },
      { name: 'body', label: 'Intro', type: 'textarea', rows: 2 },
      {
        name: 'size',
        label: 'Card size',
        type: 'select',
        width: 'half',
        default: 'compact',
        options: [
          { label: 'Compact strip', value: 'compact' },
          { label: 'Standard cards', value: 'standard' },
          { label: 'Large cards', value: 'large' },
        ],
      },
      alignField,
      {
        name: 'items',
        label: 'Features',
        type: 'list',
        fields: [
          { name: 'title', label: 'Title', type: 'text', width: 'half' },
          { name: 'icon', label: 'Icon', type: 'icon', width: 'half', default: 'star' },
          { name: 'body', label: 'Body', type: 'textarea', rows: 3 },
        ],
      },
      bgField,
    ],
    defaults: {
      eyebrow: '',
      heading: '',
      body: '',
      size: 'compact',
      align: 'center',
      background: 'white',
      items: [
        { title: 'No art or setup fees', icon: 'art', body: 'Design, revisions, names and numbers are all included.' },
        { title: '2-week rush build', icon: 'rush', body: 'Need it for a tournament? We can compress the build.' },
        { title: 'Built in-house', icon: 'factory', body: 'Sublimation, cut and sew under one roof — one point of contact.' },
        { title: 'Reorders on file', icon: 'reorder', body: 'Add a player mid-season and it matches the original kit.' },
      ],
    },
  },
  {
    type: 'ctaBand',
    label: 'CTA band',
    group: 'Conversion',
    glyph: '▬',
    description: 'Dark full-bleed band with a faded photo, headline and two buttons.',
    fields: [
      { name: 'heading', label: 'Heading', type: 'text' },
      { name: 'body', label: 'Body', type: 'textarea', rows: 2 },
      { name: 'image', label: 'Background photo', type: 'image' },
      { name: 'primary', label: 'Primary button', type: 'list', fields: linkFields },
      { name: 'secondary', label: 'Secondary button', type: 'list', fields: linkFields },
    ],
    defaults: {
      heading: 'Season starts sooner than you think',
      body: 'Send us your roster and we will have a free mockup and a firm per-unit price back to you within 24 hours.',
      image: '/media/cta-dugout.png',
      primary: [{ label: 'Request a quote', href: '#quote' }],
      secondary: [{ label: 'Call the team', href: 'tel:+19592419213' }],
    },
  },
  {
    type: 'quoteCallout',
    label: 'Quote callout',
    group: 'Conversion',
    glyph: '❯',
    description: 'Yellow panel with a short promise and a button that opens the quote drawer.',
    fields: [
      { name: 'big', label: 'Big text', type: 'text', width: 'half' },
      { name: 'heading', label: 'Heading', type: 'text', width: 'half' },
      { name: 'body', label: 'Body', type: 'textarea', rows: 2 },
      { name: 'ctaLabel', label: 'Button label', type: 'text', width: 'half' },
      { name: 'subject', label: 'Quote subject', type: 'text', width: 'half' },
    ],
    defaults: {
      big: '24h',
      heading: 'See your kit before you commit',
      body: 'Free unlimited revisions until the design is exactly what your team wants.',
      ctaLabel: 'Get my free mockup',
      subject: 'Custom team kit',
    },
  },
  {
    type: 'faq',
    label: 'FAQ accordion',
    group: 'Conversion',
    glyph: '⌄',
    description: 'Single-open accordion. Questions come from the FAQ collection, filtered by group.',
    fields: [
      { name: 'eyebrow', label: 'Eyebrow', type: 'text', width: 'half' },
      { name: 'heading', label: 'Heading', type: 'text', width: 'half' },
      {
        name: 'group',
        label: 'FAQ group',
        type: 'select',
        width: 'half',
        default: 'home',
        options: [
          { label: 'Home', value: 'home' },
          { label: 'Product', value: 'product' },
          { label: 'Contact', value: 'contact' },
        ],
      },
      { name: 'footerText', label: 'Footer text', type: 'text', width: 'half' },
      { name: 'footerCta', label: 'Footer link label', type: 'text', width: 'half' },
      bgField,
    ],
    defaults: {
      eyebrow: 'FAQ',
      heading: 'Questions, answered',
      group: 'home',
      footerText: 'Still have a question?',
      footerCta: 'Ask our team →',
      background: 'surface',
    },
  },

  // ------------------------------------------------------------- content
  {
    type: 'richText',
    label: 'Text section',
    group: 'Content',
    glyph: '¶',
    description: 'Eyebrow, heading and paragraphs. The workhorse for About / policy pages.',
    fields: [
      { name: 'eyebrow', label: 'Eyebrow', type: 'text', width: 'half' },
      { name: 'heading', label: 'Heading', type: 'text', width: 'half' },
      {
        name: 'body',
        label: 'Body',
        type: 'textarea',
        rows: 8,
        help: 'Blank line = new paragraph. **bold** and [links](/url) are supported.',
      },
      alignField,
      {
        name: 'width',
        label: 'Width',
        type: 'select',
        width: 'half',
        default: 'narrow',
        options: [
          { label: 'Narrow (readable)', value: 'narrow' },
          { label: 'Full bleed', value: 'full' },
        ],
      },
      bgField,
    ],
    defaults: {
      eyebrow: '',
      heading: 'Section heading',
      body: 'Write the section copy here.\n\nA blank line starts a new paragraph.',
      align: 'left',
      width: 'narrow',
      background: 'white',
    },
  },
  {
    type: 'imageText',
    label: 'Image + text',
    group: 'Content',
    glyph: '◧',
    description: 'Two-column split: photo on one side, copy, bullets and a CTA on the other.',
    fields: [
      { name: 'image', label: 'Image', type: 'image' },
      {
        name: 'side',
        label: 'Image side',
        type: 'select',
        width: 'half',
        default: 'left',
        options: [
          { label: 'Left', value: 'left' },
          { label: 'Right', value: 'right' },
        ],
      },
      bgField,
      { name: 'eyebrow', label: 'Eyebrow', type: 'text', width: 'half' },
      { name: 'heading', label: 'Heading', type: 'text', width: 'half' },
      { name: 'body', label: 'Body', type: 'textarea', rows: 5 },
      { name: 'bullets', label: 'Ticked bullets', type: 'tags' },
      { name: 'cta', label: 'Button', type: 'list', fields: linkFields },
    ],
    defaults: {
      image: '/media/about-workshop.png',
      side: 'left',
      background: 'white',
      eyebrow: 'Our story',
      heading: 'Built in-house since day one',
      body: 'We started in a Springfield garage printing jerseys for one travel team. Today we outfit more than a thousand programs a year — and every kit still goes through the same shop.',
      bullets: ['Sublimation, cut and sew under one roof', 'One point of contact from mockup to delivery'],
      cta: [{ label: 'Request a quote', href: '#quote' }],
    },
  },
  {
    type: 'gallery',
    label: 'Photo strip',
    group: 'Content',
    glyph: '▥',
    description: 'A row of photos — the “On the field” lookbook band.',
    fields: [
      { name: 'eyebrow', label: 'Eyebrow', type: 'text', width: 'half' },
      { name: 'heading', label: 'Heading', type: 'text', width: 'half' },
      {
        name: 'images',
        label: 'Photos',
        type: 'list',
        fields: [
          { name: 'image', label: 'Image', type: 'image', width: 'half' },
          { name: 'alt', label: 'Alt text', type: 'text', width: 'half' },
        ],
      },
      { name: 'height', label: 'Tile height (px)', type: 'number', width: 'half', min: 140, max: 520 },
      bgField,
    ],
    defaults: {
      eyebrow: 'On the field',
      heading: 'Teams wearing it now',
      height: 260,
      background: 'white',
      images: [
        { image: '/media/lookbook-1.png', alt: 'Team in custom jerseys' },
        { image: '/media/lookbook-2.png', alt: 'Player at bat' },
        { image: '/media/lookbook-3.png', alt: 'Dugout huddle' },
        { image: '/media/lookbook-4.png', alt: 'Team photo' },
      ],
    },
  },
  {
    type: 'teamGrid',
    label: 'People grid',
    group: 'Content',
    glyph: '☺',
    description: 'Portrait cards for the About page.',
    fields: [
      { name: 'eyebrow', label: 'Eyebrow', type: 'text', width: 'half' },
      { name: 'heading', label: 'Heading', type: 'text', width: 'half' },
      {
        name: 'people',
        label: 'People',
        type: 'list',
        fields: [
          { name: 'name', label: 'Name', type: 'text', width: 'half' },
          { name: 'role', label: 'Role', type: 'text', width: 'half' },
          { name: 'image', label: 'Photo', type: 'image', width: 'half' },
          { name: 'bio', label: 'Bio', type: 'textarea', rows: 2 },
        ],
      },
      bgField,
    ],
    defaults: {
      eyebrow: 'The shop',
      heading: 'Who you will be working with',
      background: 'white',
      people: [],
    },
  },
  {
    type: 'timeline',
    label: 'Milestones',
    group: 'Content',
    glyph: '⋮',
    description: 'Year / title / body milestones for the About page.',
    fields: [
      { name: 'eyebrow', label: 'Eyebrow', type: 'text', width: 'half' },
      { name: 'heading', label: 'Heading', type: 'text', width: 'half' },
      {
        name: 'items',
        label: 'Milestones',
        type: 'list',
        fields: [
          { name: 'year', label: 'Year', type: 'text', width: 'half' },
          { name: 'title', label: 'Title', type: 'text', width: 'half' },
          { name: 'body', label: 'Body', type: 'textarea', rows: 2 },
        ],
      },
      bgField,
    ],
    defaults: {
      eyebrow: 'Milestones',
      heading: 'How we got here',
      background: 'surface',
      items: [],
    },
  },

  // ------------------------------------------------------------- contact
  {
    type: 'contactForm',
    label: 'Contact form',
    group: 'Conversion',
    glyph: '✉',
    description: 'Two-column contact block: details and hours on one side, the message form on the other.',
    fields: [
      { name: 'eyebrow', label: 'Eyebrow', type: 'text', width: 'half' },
      { name: 'heading', label: 'Heading', type: 'text', width: 'half' },
      { name: 'body', label: 'Intro', type: 'textarea', rows: 3 },
      { name: 'successTitle', label: 'Success heading', type: 'text', width: 'half' },
      { name: 'successBody', label: 'Success body', type: 'textarea', rows: 2 },
      {
        name: 'hours',
        label: 'Opening hours',
        type: 'list',
        fields: [
          { name: 'days', label: 'Days', type: 'text', width: 'half' },
          { name: 'time', label: 'Time', type: 'text', width: 'half' },
        ],
      },
      { name: 'showQuoteCta', label: 'Show “need a quote instead?” panel', type: 'boolean' },
      bgField,
    ],
    defaults: {
      eyebrow: 'Contact',
      heading: 'Talk to a real person',
      body: 'Questions about sizing, fabric, artwork or timelines? Send a message and we will get back to you within one business day.',
      successTitle: 'Message sent',
      successBody: 'Thanks — we will reply to your email within one business day.',
      showQuoteCta: true,
      background: 'white',
      hours: [
        { days: 'Monday – Friday', time: '9:00 – 17:00 EST' },
        { days: 'Saturday', time: '10:00 – 14:00 EST' },
        { days: 'Sunday', time: 'Closed' },
      ],
    },
  },
  {
    type: 'mapEmbed',
    label: 'Map',
    group: 'Content',
    glyph: '⌖',
    description: 'Embedded map iframe with the shop address.',
    fields: [
      { name: 'heading', label: 'Heading', type: 'text', width: 'half' },
      { name: 'height', label: 'Height (px)', type: 'number', width: 'half', min: 200, max: 700 },
      {
        name: 'src',
        label: 'Embed URL',
        type: 'text',
        help: 'Google Maps → Share → Embed a map → copy the src URL.',
      },
      bgField,
    ],
    defaults: {
      heading: 'Find the shop',
      height: 420,
      src: 'https://www.google.com/maps?q=1601+Main+St,+Springfield,+Massachusetts+01103&output=embed',
      background: 'white',
    },
  },

  // ------------------------------------------------------------- layout
  {
    type: 'spacer',
    label: 'Spacer / divider',
    group: 'Layout',
    glyph: '—',
    description: 'Vertical space, optionally with a hairline rule.',
    fields: [
      { name: 'height', label: 'Height (px)', type: 'number', width: 'half', min: 0, max: 240 },
      { name: 'rule', label: 'Show hairline', type: 'boolean', width: 'half' },
      bgField,
    ],
    defaults: { height: 60, rule: false, background: 'white' },
  },
  {
    type: 'html',
    label: 'Custom HTML',
    group: 'Layout',
    glyph: '</>',
    description: 'Raw HTML escape hatch for embeds. Admin-only — inserted as-is.',
    fields: [
      { name: 'html', label: 'HTML', type: 'textarea', rows: 10 },
      bgField,
    ],
    defaults: { html: '<p>Custom HTML</p>', background: 'white' },
  },
];

export const BLOCK_MAP: Record<string, BlockDefinition> = Object.fromEntries(
  BLOCKS.map((b) => [b.type, b])
);

export function blockDef(type: string) {
  return BLOCK_MAP[type];
}

export const BLOCK_GROUPS = [
  'Hero & headers',
  'Commerce',
  'Conversion',
  'Social proof',
  'Content',
  'Layout',
] as const;

export const ICON_CHOICES = [
  'chat',
  'clock',
  'check',
  'truck',
  'art',
  'rush',
  'factory',
  'reorder',
  'star',
  'shield',
  'phone',
  'mail',
  'pin',
  'ruler',
  'palette',
  'tag',
] as const;
